parserOptions:
  sourceType: module
  ecmaVersion: 2022
  ecmaFeatures:
    jsx: true

settings:
  react:
    version: detect

env:
  browser: true

plugins:
  - eslint-plugin-react

extends:
  - eslint:recommended
  - plugin:react/recommended

rules:
  react/prop-types: off
